version: "3.9"
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    networks:
      - my-net
    healthcheck:
      test: nc -z localhost 8080 || exit
      interval: 10s
      timeout: 5s
      retries: 15

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "always"
    ports:
      - "2181:2181"
      - "9093:9093"
      - "29092:29092"
    env_file:
      - .env
    healthcheck:
      test: nc -z localhost 29092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - my-net
    depends_on:
      kafka-ui:
        condition: service_healthy
    volumes:
      - ./create-topics.sh:/create-topics.sh
    command: ["sh", "-c", "kafka-server-start.sh /etc/kafka/server.properties & sleep 5 && sh /create-topics.sh && tail -f /dev/null"]

networks:
  my-net:
    driver: bridge
